### ISSUE TITLE
not working with Openfire 4.5.1

### ISSUE THREAD

**Issue by ioscanner** [igniterealtime/openfire-pushnotification-plugin#2]
I have been trying to get this module to work for a week now.  I am not sure if the issues is the plugin or a bug in Openfire 4.5.1 with s2s connections.  I even had the developer at Monal.im confirm that it is not opening the s2s connection on a push as it should.  S2s is working to other servers.

Thank for your hard work on this project.

**Comment by guusdk** [comment]
Up until moments ago, there was not a proper release of the Openfire Push Notification plugin. This required you to use a development build. These builds get updated all the time. A while ago, a breaking change was introduced, which very likely causes your issues. Just now, we've released version 0.6.0 of the Push Notification plugin. I've tested this with the developer of Monal. In our tests, push notifications were transmitted as expected. I advise you to replace your development build (0.7.0-SNAPSHOT) with release 0.6.0 (which is not a development build, and more stable).
