### ISSUE TITLE
Enable-request without options fails

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-pushnotification-plugin#22]
The Push Notification plugin should not fail processing a request to enable push notifications, when that request does not contain optional publication options.

Currently, the plugin incorrectly states that, in such cases, the push service for the specified node / user was already registered.

**Comment by guusdk** [comment]
Siskin is affected by this, as it doesn't currently appear to send any options with the 'enable' request.

**Comment by guusdk** [comment]
@pd888 Would you mind help testing the fix for this problem? The fix is available in any 'snapshot' build for the plugin that was created on or after 'Feb 3, 2021 3:23:31 PM'. You can download these snapshots from the plugin archive page at https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=pushnotification

**Comment by pd888** [comment]
Sure @guusdk i'm happy to test it out, I will post results here.

**Comment by pd888** [comment]
@guusdk I rebuilt my server for good measure and tested using 0.8.0 of push notfications. 
Happy to report success! Push is now working. 🥇 

Thank you for all your help.

**Comment by guusdk** [comment]
Ah, thanks! I've pushed the release: https://discourse.igniterealtime.org/t/push-notification-openfire-plugin-0-8-0-released/

Thanks for your help in reporting, analyzing and fixing this!
