### ISSUE TITLE
NPE encountered if there are no "options" specified for the Push node for a user.

### ISSUE THREAD

**Issue by oneeyedraven** [igniterealtime/openfire-pushnotification-plugin#25]
Steps to reproduce:
1. "Enable" the push notification by sending the IQ packet to the server: <iq id='3V36N-39' type='set'>
```
      <enable xmlns='urn:xmpp:push:0' jid='testuser1@openfire' node='pusher@openfire'/>
    </iq>
```
2. Try sending a message to testuser1 while it is offline.

Result:
NPE Observered, with the following trace:

> 2021.03.30 16:16:11 org.igniterealtime.openfire.plugins.pushnotification.PushServiceManager - Unable to process database row content while obtaining push service configuration for user 'testuser2'.
> java.lang.NullPointerException: null
> at java.io.StringReader.<init>(StringReader.java:50) ~[?:1.8.0_251]
> at org.igniterealtime.openfire.plugins.pushnotification.PushServiceManager.getServiceNodes(PushServiceManager.java:160) [pushnotification-0.8.0.jar!/:?]
> at org.igniterealtime.openfire.plugins.pushnotification.Push0IQHandler.handleIQ(Push0IQHandler.java:137) [pushnotification-0.8.0.jar!/:?]

**Comment by guusdk** [comment]
This issue has also been reported here: https://discourse.igniterealtime.org/t/still-push-notification-issues/91519

**Comment by guusdk** [comment]
Please help me test the fix by trying the [SNAPSHOT build of this plugin](https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=pushnotification) that was created on, or later than May 11, 2022 7:11:44 AM.
